In [3]:
print("布尔型")
print("浮点型")
print("整数型")

布尔型
浮点型
整数型


<class 'numpy.ndarray'>
[ 15.145  15.239  15.353  15.528  15.736]


In [ ]:
s = ['y', 'o', 'y','o']
s[:]

In [ ]:
import numpy as np
import pandas as pd
import warnings
import talib as ta
import pandas as pd
warnings.filterwarnings('ignore')

from datetime import datetime

symbol=['600029.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data['close']
data = pd.DataFrame(data_dict)

print(data.iloc[:])

In [ ]:
data=pd.read_excel('sz50.xlsx',sheetname=None,index_col='datetime')

MA = ta.MA(data['600029.XSHG'].close.values,10)
print(type(MA))
print(MA[-5:]

In [5]:
import warnings
warnings.filterwarnings('ignore')
from datetime import datetime
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data.loc[:]
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


In [6]:
import numpy as np
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data = pd.read_excel('sz50.xlsx', symbol, index_col='datetime')
print(data.iloc[-20:])

AttributeError: 'collections.OrderedDict' object has no attribute 'iloc'

In [7]:
arr1 = np.arange(25).reshape(5,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
